### ISSUE TITLE
change mesh.child to something else

### ISSUE THREAD

**Issue by crcn** [mojo-js/mesh.js#116]
because of cases like this:

```javascript
var bus = mesh.parallel();
users = mesh.child(bus, { collection: "user" });
friends = mesh.child(bus, { collection: "friend" });
```

something that describes that properties are getting attached to each operation. Ideas:

`glue`, `attach`, `addon`, `bind`, `copy`, `merge`, `hitch`

Hitch seems like the most appropriate name to use as an alternative

**Comment by fouad** [comment]
Of those options, I think `attach` makes the most sense.

**Comment by crcn** [comment]
hmm - yeah I like that:

```javascript
mesh.attach({ collection: "user" }, bus);
```

**Comment by fouad** [comment]
What about bus.attach({ collection: "user" });



Fouad

**Comment by crcn** [comment]
hmm - only thing is that this sorta falls out of convention. Something like this wouldn't be possible:

```javascript
var db = memory();

var bus = mesh.parallel(
  mesh.accept("loadUsers", mesh.attach(mesh.op("load", { collection: "users" }), db))
);

bus(mesh.op("loadUsers")).on("data", function() {

});
```

Also, keep in mind that `mesh.attach` already works like `bus.attach`. For example:

```javascript
var db   = memory(); 
var bus = db;

bus = mesh.attach({ a: 1 }, bus);
bus = mesh.attach({ b: 2 }, bus); // just takes options from previous bus

console.log(bus.target === db); // true
```

Basically, `mesh.attach` just merges options from the previous bus if it already has attached options.

https://github.com/mojo-js/mesh.js/blob/master/lib/attach.js#L7
